### ISSUE TITLE
Unable to understand terraform 0.12 configuration

### ISSUE THREAD

**Issue by tmccombs** [pulumi/tf2pulumi#202] opened 2020-07-29 23:04 UTC
I'm trying to run tf2pulumi on a codebase of terraform 0.12 configuration, and have run into several issues:

- [ ] Even with `--allow-missing-plugins` it fails if there resources that use builtin providers such as `terraform_remote_state` or `archive_file` (see #133  and #172 )
- [ ] References to module outputs result in `undefined variable module`
- [ ] For resource that use `for_each` I get the error "undefined variable range"
- [ ] calls to `toset`, `concat`, and `values` result in `unknown function ...` (#12)
- [ ] References to the `readerEndpoint` property of an aurora cluster results in `unknown property 'readerEndpoint'`

Unfortunately, these make tf2pulumi unusable for my existing codebase.

**Comment by LionsAd** [comment] 2020-08-03 12:17
I agree - I also tried tf2pulumi on two terraform code bases and both failed miserably:

- One was not able to do anything as all terraform is in sub-directories

- The other continued a little bit, but then did not use the provided plugins

In both cases I not even had any stub to work with.

**Comment by Frassle** [comment] 2022-12-07 10:23
I'm going to close this off as a dupe of https://github.com/pulumi/tf2pulumi/issues/186

**Closed** 2022-12-07 10:23 UTC
Labels: kind/bug, resolution/duplicate
