### ISSUE TITLE
Example broken for `getSubnetIds`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/tf2pulumi#101] opened 2019-04-23 18:23 UTC
This example is broken (in several different ways):

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ec2/getSubnetIds.ts#L24

A "correct' version of this is:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

async function getAllSubnets(): Promise<aws.ec2.GetSubnetResult[]> {
    const subnetIds = await aws.ec2.getSubnetIds({
        vpcId: "vpc-c93b06ae",
    });

    const results: aws.ec2.GetSubnetResult[] = [];
    for (const subnetId of subnetIds.ids) {
        const subnet = await aws.ec2.getSubnet({
            id: subnetId,
        });
        results.push(subnet);
    }

    return results;
}

export const allSubnets = getAllSubnets();
```

**Comment by pgavlin** [comment] 2019-05-16 20:07
Closing as a duplicate of #63.

**Closed by pgavlin** 2019-05-16 20:07 UTC

**Comment by tdpauw** [comment] 2021-02-05 21:46
IMHO, this is not a duplicate of #63.

That said, the example in the current documentation of `aws.ec2.getSubnetIds` is still broken.
https://www.pulumi.com/docs/reference/pkg/aws/ec2/getsubnetids/

The example provided by @lukehoban is a correction version. It would be good to include that one in the documentation.
