### ISSUE TITLE
"default provider configuration is not supported" converting example EKS Terraform

### ISSUE THREAD

**Issue by markfickett** [pulumi/tf2pulumi#245] opened 2021-11-10 20:33 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm attempting to convert https://github.com/hashicorp/learn-terraform-provision-eks-cluster to Pulumi (in Python).

### Steps to reproduce
1. Install Pulumi (shell install, v3.17.0)
2. Install tf2pulumi (linux binary x64, v0.11.1)
3. install aws and pulumi_random resources
4. execute `tf2pulumi --target-language python`:

Expected: convert without errors
Actual: "Warning: default provider configuration is not supported" shows up in output, along with a few other "undefined variable module" errors

```
Warning: default provider configuration is not supported

  on kubernetes.tf line 7:
  (source code not available)

Warning: default provider configuration is not supported

  on vpc.tf line 15:
  (source code not available)
```

**Comment by leezen** [comment] 2021-11-12 14:15
Closing as a dupe of #244 

Separately, have you looked at the `pulumi_eks` package for your EKS cluster provisioning needs? https://github.com/pulumi/pulumi-eks

**Closed by leezen** 2021-11-12 14:15 UTC
Labels: kind/bug, resolution/duplicate

**Comment by markfickett** [comment] 2021-11-12 15:13
Thanks for the `pulumi_eks` pointer, it's great that it includes examples in a variety of languages including Python. I'm new to Kubernetes as well as Pulumi so I was relying on the Terraform example to get my cluster set up correctly, which was why my first approach was to use `tf2pulumi`, but hopefully `pulumi_eks` will get me on the right track too!
